AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a knowledge-base search tool

Parameters:

  CloudTrailS3Bucket:
    Type: String
    Description: This is the bucket where your cloudtrail logs feed into

Resources:

  #############################################################################
  ## S3 BUCKET                                                               ##
  #############################################################################

  ShorelineS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub shoreline-bucket-${AWS::Region}-${AWS::AccountId}
  
  #############################################################################
  ## Neptune                                                                 ##
  #############################################################################

  Type: "AWS::Neptune::DBCluster"
  Properties:
    AvailabilityZones:
      - String
    BackupRetentionPeriod: Integer
    DBClusterIdentifier: String
    DBClusterParameterGroupName: String
    DBSubnetGroupName: String
    IamAuthEnabled: Boolean
    KmsKeyId: String
    Port: Integer
    PreferredBackupWindow: String
    PreferredMaintenanceWindow: String
    SnapshotIdentifier: String
    StorageEncrypted: Boolean
    Tags:
      - Resource Tag
    VpcSecurityGroupIds:
      - String

  #############################################################################
  ## IAM Role                                                                ##
  #############################################################################

  Type: AWS::IAM::Role
  Properties: 
    AssumeRolePolicyDocument:
      JSON object
    ManagedPolicyArns:
      - String
    MaxSessionDuration: Integer
    Path: String
    PermissionsBoundary: String
    Policies:
      - Policiesd
    RoleName: String

  #############################################################################
  ## EC2 Instance                                                            ##
  #############################################################################
  
  Type: AWS::EC2::Instance
  Properties: 
    Affinity: String
    AvailabilityZone: String
    BlockDeviceMappings: 
      - EC2 Block Device Mapping
    CreditSpecification: CreditSpecification
    DisableApiTermination: Boolean
    EbsOptimized: Boolean
    ElasticGpuSpecifications: [ ElasticGpuSpecification, ... ]
    HostId: String
    IamInstanceProfile: String
    ImageId: String
    InstanceInitiatedShutdownBehavior: String
    InstanceType: String
    Ipv6AddressCount: Integer
    Ipv6Addresses:
      - IPv6 Address Type
    KernelId: String
    KeyName: String
    LaunchTemplate: LaunchTemplateSpecification
    Monitoring: Boolean
    NetworkInterfaces: 
      - EC2 Network Interface
    PlacementGroupName: String
    PrivateIpAddress: String
    RamdiskId: String
    SecurityGroupIds: 
      - String
    SecurityGroups: 
      - String
    SourceDestCheck: Boolean
    SsmAssociations: 
      - SSMAssociation
    SubnetId: String
    Tags: 
      - Resource Tag
    Tenancy: String
    UserData: String
    Volumes: 
      - EC2 MountPoint
    AdditionalInfo: String

  #############################################################################
  ## EC2 Instance                                                            ##
  #############################################################################
  
  Outputs:
  ApiEndpoint:
    Description: "Security Fairy Invocation Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start"